# Generated by Django 6.0.3 on 2026-05-10 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='yandex_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
