# Generated by Django 6.0.3 on 2026-05-31 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_yandex_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyerprofile',
            name='favorite_categories',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='buyerprofile',
            name='total_purchases',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='total_sales',
            field=models.IntegerField(default=0),
        ),
    ]
