# Generated by Django 6.0.3 on 2026-05-31 13:03

import apps.labs.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('level', models.CharField(choices=[('bachelor', 'Бакалавриат'), ('specialist', 'Специалитет'), ('master', 'Магистратура'), ('postgraduate', 'Аспирантура')], max_length=15)),
                ('course', models.IntegerField(validators=[apps.labs.models.validate_course])),
                ('year', models.CharField(max_length=4)),
                ('university', models.CharField(max_length=200)),
                ('faculty', models.CharField(max_length=200)),
                ('type_work', models.CharField(choices=[('laboratory', 'Лабораторная'), ('essay', 'Реферат'), ('coursework', 'Курсовая'), ('diploma', 'ВКР')], max_length=15)),
                ('author', models.CharField(blank=True, max_length=200, null=True)),
                ('manager', models.CharField(blank=True, max_length=200, null=True)),
                ('downloaded_times', models.IntegerField(default=0)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='LabFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='lab_files/')),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='labs.lab')),
            ],
        ),
    ]
